export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_INIT = 'USER_INIT'
export const USER_INIT_FAULT = 'USER_INIT_FAULT'
export const USER_LOADING = 'USER_LOADING'

export const GROUPS_LOADING = 'GROUPS_LOADING'
export const GROUPS_LOADING_SUCCESS = 'GROUPS_LOADING_SUCCESS'
export const GROUPS_LOADING_FAULT = 'GROUPS_LOADING_FAULT'
